surge-ai/surge-python

README.md, setup.py, surge/errors.py, surge/projects.py, surge/tasks.py, surge/utils.py
- Use new endpoint to create tasks in bulk
- Implement basic bulk upload of tasks from CSV
=> Implement bulk task creation

README.md, surge/api_resource.py, surge/projects.py, surge/questions.py, surge/tasks.py
Closes #4.
Now the Project and Task objects will be shown in the console as
`<surge.Project#9ac59d54-7455-4dce-b30b-68d449020034 name="Test project created using the apis" fields_template="None" num_workers_per_task="1" status="unlaunched" created_at="2021-02-11T16:36:05.008Z" num_tasks_completed="0" num_responses_completed="0" instructions="None" num_tasks="0" link_to_work_on_task="https://app.surgehq.ai/workers/tasks?project_id=9ac59d54-7455-4dce-b30b-68d449020034" avg_gold_standard_score="0" interrater_agreement="{}" questions="[]">`
=> Show all object attributes in __repr__

requirements.txt, setup.py, surge/api_resource.py, surge/projects.py, surge/responses.py, surge/tasks.py
- Create datetime objects from timestamp strings
- Update requirements file so that new versions don't have breaking changes
- Print entire body of response after http error
=> Datetimes for timestamp fields + Update requirements file + Print more details after http error

README.md, setup.py, surge/errors.py, surge/projects.py, surge/tasks.py, tests/test_api_resource.py, tests/test_projects.py, tests/test_tasks.py
- Convert the `questions` attribute in projects into objects
- Add unit tests for APIResource, Projects, Tasks
- Catch more exceptions during init
- Add testing instructions to readme
=> Unit tests and misc fixes

surge/tasks.py
API endpoint PR: https://github.com/surge-ai/gondor/pull/2924
=> Add support for worker response endpoint

surge/tasks.py
Gondor PR: https://github.com/surge-ai/gondor/pull/2978
=> Add worker param to task response endpoint

setup.py
I think someone else has to publish the new version who has access to PyPi for this SDK.
=> version 1.0.13

surge/api_resource.py, surge/projects.py, surge/questions.py, surge/reports.py, surge/responses.py, surge/tasks.py
Changed according to [YAPF](https://github.com/google/yapf)
=> Style fixes to comply with PEP8

setup.py, surge/projects.py, surge/questions.py
Adding SDK support for this endpoint: https://app.surgehq.ai/docs/api#list-all-projects-in-your-organization
=> Add endpoint to list shared projects

setup.py, surge/reports.py
Usage example:
```
import pandas as pd
import surge
surge.Report.save_report(project_id, 'export_csv', 'my_data.csv')
df = pd.read_csv('my_data.csv')
```
=> Add function to poll for and download+unzip reports

setup.py, surge/projects.py, surge/questions.py, tests/test_projects.py
Flagged by Frasier here: https://surge-ai.slack.com/archives/C039K6QBNNT/p1667388064217409
Not sure what the deploy process for this is like
tested via unit tests
=> Fix text area in SDK

surge/api_resource.py, surge/questions.py
This allows users to specify a column header for each question. If it is set, we will use the column header param to generate results csv and json files. If it is null, we will fall back on the question text.
=> Add support for column header param

surge/tasks.py
=> Update set_gold_standard to return task object

setup.py, surge/projects.py
Changing this parameter name for clarity.
=> Rename copy_from_project_id to template_id

setup.py, surge/projects.py
=> feat: add Project.list_copies

setup.py, surge/api_resource.py, surge/projects.py, surge/questions.py, surge/reports.py, surge/tasks.py, surge/teams.py, tests/test_api_resource.py, tests/test_projects.py
tested end-to-end on local
some tests were already busted in the main branch, fixed those
=> Allow passing in api key

setup.py, surge/projects.py, surge/questions.py
Request from Edwin for Meta and Milad from Google
```
import surge
surge.api_key = "7H6C3AGFT7RY99VA7QVNXE6R"
project = surge.Project.retrieve("33fd022e-b33b-4faf-b394-ad0548ff6739")
project.questions[0].label # verify this has a value
project.questions[0].question_category # verify this is set
project.to_json() # verify this looks correct
```
=> Add question_category, label to questions and to_json to project

surge/api_resource.py
Tested by hitting API with a test file and project
=> Marginally improve API error messages

setup.py, surge/projects.py
To be merged after https://github.com/surge-ai/gondor/pull/15583
=> Support project filtering in external surge SDK

setup.py, surge/projects.py
Adds pagination to blueprints API. This is actually already handled in our external API code, just was never added to the python SDK
https://github.com/surge-ai/gondor/pull/15085
=> Add pagination to blueprints SDK

surge/api_resource.py, tests/test_api_resource.py, tests/test_projects.py
Add support for file uploads for future APIs
Unit tests
=> Add support for post file uploads

setup.py, surge/api_resource.py, tests/test_api_resource.py
=> Fix uploads with parameters

setup.py, surge/projects.py, tests/test_projects.py
I also noticed `fields_template` was defined but not used, so I added an implementation.
=> Add a way to provide arbitrary properties to Project.update

surge/api_resource.py, surge/projects.py, surge/questions.py, surge/reports.py, surge/responses.py, tests/test_api_resource.py, tests/test_projects.py
=> format files with yapf

setup.py, surge/reports.py
Return the raw binary data from save_report
=> Return data raw data from save_report

surge/api_resource.py, surge/projects.py, surge/reports.py, surge/tasks.py, tests/test_reports.py
=> Formatting
